GET http://localhost:3001/todos

###

POST http://localhost:3001/todo/new
Content-Type: application/json

{
    "text": "hello hari"
}

###

DELETE http://localhost:3001/todo/delete/64058efc9639849dfca04628

###
PUT http://localhost:3001/todo/complete/64045ff4d3c76e24bd1266d0